### ISSUE TITLE
Any way to get the user name or email address from messenger?

### ISSUE THREAD

**Issue by kofarrell1076** [eternaltung/MessengerBot-WebAPI#2]
Hi,
Your control works well. good work. Is there any way I can get the sending users name (first/last) and or the email address? I'm trying to find a way to match the incoming with an existing contact manager.

thanks

**Comment by eternaltung** [comment]
Hi,
Yes, you can get the users first/last name via the following user profile API.
https://developers.facebook.com/docs/messenger-platform/user-profile
